name: Array API Compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC

# torch doesn't have wheels for 3.14 yet
env:
  latest_python: "3.13"

jobs:
  test:
    name: Array API (${{ matrix.backend }})
    runs-on: gpu-t4-4-core
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: torch
            device: cuda
          # - backend: jax
          # - backend: cupy
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.latest_python }}
      - name: Check CUDA
        run: nvidia-smi
      - name: Install scikit-bio + backend
        run: |
          python -m ensurepip
          pip install --no-deps .
          pip install ${{ matrix.backend }}
          pip install -r ci/requirements.txt -r ci/requirements.test.txt
      - name: Run tests
        env:
          SKBIO_ARRAY_BACKEND: ${{ matrix.backend }}
          SKBIO_DEVICE: ${{ matrix.device }}
        run: pytest skbio/stats/composition/tests/test_base.py
