name: Array API Compatibility

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'   # Every Monday at 06:00 UTC

env:
  latest_python: "3.14"

jobs:
  test:
    name: Array API (${{ matrix.backend }})
    runs-on: ubuntu-latest # gpu-t4-4-core
    strategy:
      fail-fast: false
      matrix:
        include:
          - backend: torch
          - backend: jax
          - backend: cupy
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.latest_python }}
      - name: Check CUDA
        run: nvcc --version
      - name: Install scikit-bio + backend
        run: |
          python -m ensurepip
          pip install --no-deps .
          pip install ${{ matrix.backend }}
          pip install -r ci/requirements.txt -r ci/requirements.test.txt
      - name: Run tests
        env:
          SKBIO_ARRAY_BACKEND: torch # ${{ matrix.backend }}
          SKBIO_DEVICE: cpu
        run: python -m skbio.test
